export const mockUser = {
  id: 'usr_001',
  name: 'Alex Morgan',
  email: 'alex.morgan@example.com',
  avatar: null,
  timezone: 'America/New_York',
  language: 'en',
  gmailConnected: true,
  telegramConnected: true,
  preferences: {
    emailDigest: true,
    pushAlerts: true,
    marketing: false,
  },
}

export const mockStats = {
  total: 128,
  scheduled: 24,
  sent: 98,
  failed: 6,
  channelDistribution: [
    { channel: 'Telegram', count: 52, percentage: 41 },
    { channel: 'Gmail', count: 38, percentage: 30 },
    { channel: 'Both', count: 38, percentage: 29 },
  ],
  weeklyActivity: [
    { day: 'Mon', sent: 12, failed: 1 },
    { day: 'Tue', sent: 18, failed: 0 },
    { day: 'Wed', sent: 15, failed: 2 },
    { day: 'Thu', sent: 22, failed: 1 },
    { day: 'Fri', sent: 19, failed: 0 },
    { day: 'Sat', sent: 8, failed: 1 },
    { day: 'Sun', sent: 4, failed: 1 },
  ],
}

export const mockNotifications = [
  {
    id: 'ntf_001',
    title: 'Weekly Team Standup',
    message: 'Reminder: Join the standup meeting at 10 AM.',
    channel: 'both',
    date: '2026-05-31',
    time: '09:45 AM',
    status: 'pending',
    recurring: true,
    recurrence: 'weekly',
    createdAt: '2026-05-28T10:00:00Z',
  },
  {
    id: 'ntf_002',
    title: 'Invoice Payment Due',
    message: 'Your subscription renews tomorrow. Please review billing.',
    channel: 'gmail',
    date: '2026-05-29',
    time: '08:00 AM',
    status: 'sent',
    recurring: false,
    recurrence: null,
    createdAt: '2026-05-27T14:30:00Z',
  },
  {
    id: 'ntf_003',
    title: 'Server Health Check',
    message: 'Automated health check report for production cluster.',
    channel: 'telegram',
    date: '2026-05-28',
    time: '11:30 PM',
    status: 'failed',
    recurring: true,
    recurrence: 'daily',
    createdAt: '2026-05-26T09:15:00Z',
  },
  {
    id: 'ntf_004',
    title: 'Birthday Reminder',
    message: "Don't forget Sarah's birthday party this weekend!",
    channel: 'telegram',
    date: '2026-06-01',
    time: '07:00 AM',
    status: 'pending',
    recurring: false,
    recurrence: null,
    createdAt: '2026-05-25T16:45:00Z',
  },
  {
    id: 'ntf_005',
    title: 'Monthly Report',
    message: 'Generate and send the monthly analytics report.',
    channel: 'both',
    date: '2026-06-01',
    time: '06:00 PM',
    status: 'pending',
    recurring: true,
    recurrence: 'monthly',
    createdAt: '2026-05-24T11:00:00Z',
  },
  {
    id: 'ntf_006',
    title: 'Medication Reminder',
    message: 'Time to take your evening medication.',
    channel: 'gmail',
    date: '2026-05-27',
    time: '08:00 PM',
    status: 'sent',
    recurring: true,
    recurrence: 'daily',
    createdAt: '2026-05-23T08:00:00Z',
  },
  {
    id: 'ntf_007',
    title: 'Client Follow-up',
    message: 'Follow up with Acme Corp regarding the proposal.',
    channel: 'gmail',
    date: '2026-05-30',
    time: '02:00 PM',
    status: 'pending',
    recurring: false,
    recurrence: null,
    createdAt: '2026-05-22T13:20:00Z',
  },
  {
    id: 'ntf_008',
    title: 'Backup Verification',
    message: 'Verify nightly backup completion status.',
    channel: 'telegram',
    date: '2026-05-26',
    time: '05:00 AM',
    status: 'sent',
    recurring: true,
    recurrence: 'daily',
    createdAt: '2026-05-21T07:30:00Z',
  },
]

export const mockRecentActivity = [
  { id: 'act_1', action: 'Notification sent', target: 'Invoice Payment Due', time: '2 hours ago', type: 'success' },
  { id: 'act_2', action: 'Notification failed', target: 'Server Health Check', time: '5 hours ago', type: 'error' },
  { id: 'act_3', action: 'Notification scheduled', target: 'Weekly Team Standup', time: '1 day ago', type: 'info' },
  { id: 'act_4', action: 'Gmail connected', target: 'Account settings', time: '2 days ago', type: 'success' },
  { id: 'act_5', action: 'Notification sent', target: 'Medication Reminder', time: '3 days ago', type: 'success' },
]
